[package]
name = "lf"
version = "0.1.0"
authors = ["sleefd sleefd@gmail.com"]
description = "Locate a file in file explorer"
repository = "https://github.com/reminia/lf-rs"
license = "MIT"
keywords = ["cli", "open", "file"]
edition = "2021"

[dependencies]