[package]
name = "lf"
version = "0.2.0"
authors = ["sleefd sleefd@gmail.com"]
description = "Locate a file in file explorer"
repository = "https://github.com/reminia/lf-rs"
license = "MIT"
keywords = ["open", "select", "focus"]
edition = "2021"

[dependencies]